project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Challenge 1 Fundamentals of Machine Learning"
            file: C:/Users/Lenovo/OneDrive/Desktop/daqtascience/ss24-bdml-Fahad221999/Chapter_1_Challenge_fahad.qmd
          - text: "Challenge 2 Supervised ML"
            file: C:/Users/Lenovo/OneDrive/Desktop/daqtascience/ss24-bdml-Fahad221999/Chapter_2_Challenge-Fahad.qmd
          - text: "Challenge 3 Automated Machine Learning with H2O (I)"
            file: C:/Users/Lenovo/OneDrive/Desktop/daqtascience/ss24-bdml-Fahad221999/Chapter_3_Challenge_fahad.qmd
          - text: "Challenge 3b and 4 Automated Machine Learning with H2O (II) and Precision Measuring"
            file: C:/Users/Lenovo/OneDrive/Desktop/daqtascience/ss24-bdml-Fahad221999/Chapter_3b _and_4_Challenge_fahad.qmd
          - text: "Challenge 5 Lime"
            file: C:/Users/Lenovo/OneDrive/Desktop/daqtascience/ss24-bdml-Fahad221999/05_lime.qmd
            
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd
exclude:
  - ".Rhistory"
  - "**/Chapter_1_Challenge_fahad_files/**"
format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto